# Generated by Django 6.0.7 on 2026-07-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_library', '0002_alter_video_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-created_at']},
        ),
    ]
